### ISSUE TITLE
New `list_item` check

### ISSUE THREAD

**Issue by madeinussr** [madeinussr/exop#15]
It would be useful to have `list_item` check for a list parameter's item validation.

```elixir
parameter :some_list, type: :list, list_item: %{type: :string, length: %{min: 7}}
```

In the code above the `list_item` should check every `:some_list` parameter's item: whether it conforms given check requirements.

For this declaration here are some outputs depend on `some_list` value passed to an Operation:

1. `some_list = ["1234567", 1, "123"]`, validation result:
```elixir
{:error, {:validation,%{item_1: ["has wrong type", "length must be greater than or equal to 7"],
                                    item_2: ["length must be greater than or equal to 7"]}}}
```

2. `some_list = ["1234567", "7charss"]`, validation result:
```elixir
:ok
```

As you've noticed, an error should refer exact item (with index) in order to provide some clue for debugging: `item_2: ["length must be greater than or equal to 7"]` (means item with index 2 (starts from 0) in a list has the error).

`coerce_with` and `default` should work properly with this check, along with more complex `inner` check.

Here are some tests that should pass:

```
  test "valid?/2: validates a list parameter items with list_item option checks (simple)" do
    contract = [
      %{
        name: :list_param,
        opts: [
          type: :list,
          list_item: %{type: :string, length: %{min: 7}}
        ]
      }
    ]

    received_params = [
      list_param: [1, "6chars", nil, "7charss"]
    ]

    {:error, {:validation, reasons}} = valid?(contract, received_params)

    assert %{
      item_0: ["has wrong type", "length must be greater than or equal to 7"],
      item_1: ["length must be greater than or equal to 7"],
      item_2: ["length must be greater than or equal to 7"]
    } == reasons
  end

  test "valid?/2: validates a list parameter items with list_item option checks (inner)" do
    contract = [
      %{
        name: :list_param,
        opts: [
          type: :list,
          list_item: %{inner: %{
            a: %{type: :integer, required: true},
            b: %{type: :string, length: %{min: 7}}
          }}
        ]
      }
    ]

    received_params = [
      list_param: [
        %TestStruct{a: 3, b: "6chars"},
        %TestStruct{a: nil, b: "7charss"}
      ]
    ]

    {:error, {:validation, reasons}} = valid?(contract, received_params)

    assert %{
      a: ["is required"],
      b: ["length must be greater than or equal to 7"]
    } == reasons
  end

  test "valid?/2: validates a list parameter items with list_item option checks (not list)" do
    contract = [
      %{
        name: :list_param,
        opts: [
          list_item: %{type: :string, length: %{min: 7}}
        ]
      }
    ]

    received_params = [
      list_param: 1
    ]

    {:error, {:validation, reasons}} = valid?(contract, received_params)

    assert %{list_param: ["is not a list"]} == reasons
  end

  test "valid?/2: validates a list parameter items with list_item option checks (success)" do
    contract = [
      %{
        name: :list_param,
        opts: [
          list_item: %{type: :string, length: %{min: 7}}
        ]
      }
    ]

    received_params = [
      list_param: ["1234567", "7charss"]
    ]

    assert valid?(contract, received_params) == :ok
  end
```

and

```
  test "list_item + default value" do
    defmodule TestOperation do
      use Exop.Operation

      parameter :param, list_item: %{type: :string, length: %{min: 7}}, default: ["1234567", "7chars"]

      def process(params) do
        {:ok, params[:param]}
      end
    end

    assert TestOperation.run() == {:error, {:validation, %{item_1: ["length must be greater than or equal to 7"]}}}
  end

  test "list_item + coerce_with" do
    defmodule TestOperation do
      use Exop.Operation

      parameter :param, list_item: %{type: :string, length: %{min: 7}}, coerce_with: &__MODULE__.make_list/1

      def process(params) do
        {:ok, params[:param]}
      end

      def make_list(_), do: ["1234567", "7chars"]
    end

    assert TestOperation.run() == {:error, {:validation, %{item_1: ["length must be greater than or equal to 7"]}}}
  end
```

**Comment by madeinussr** [comment]
@johnhamelink hi! How is your progress?

**Comment by johnhamelink** [comment]
Hey @madeinussr I've been busy launching our product over the past few weeks. Once we've done that this is a top priority for me 😄

**Comment by madeinussr** [comment]
Hi @johnhamelink dont want to force you :) but if you have some issues with implementing, I can deliver my implementation, as I said before. Or mb you need some advice?

**Comment by johnhamelink** [comment]
Hey @madeinussr so I began writing an implementation, and ended up with something quite different from what you advised. However I still wasn't happy, with what I'd done, so I ended up using https://github.com/bcoop713/skooma with a macro to emulate the behaviour of exop

**Comment by madeinussr** [comment]
@johnhamelink and in order to summarise your effort: are you going to contribute smth to exop or it would be better I'll add this feature? Will this feature be helpful for you?
Anyway, thank you for your work! Your advise and proposition for a new check is valuable from my perspective.

**Comment by johnhamelink** [comment]
@madeinussr apologies for not being clear: I don't think my work is good enough to contribute. I am happy to share it and get your thoughts, but I've decided that for our solution we will use Skooma instead as it fitted our requirements instead.

https://github.com/madeinussr/exop/compare/master...johnhamelink:feature/nested-validation?expand=1
