### ISSUE TITLE
Dialyzer warnings

### ISSUE THREAD

**Issue by smanolloff** [madeinussr/exop#16]
I am using exop like so:
```elixir
defmodule MyModule do
  use Exop.Operation

  parameter :format, type: :string, in: ~w[json csv]
  parameter :from, required: true, type: :string
  parameter :to, required: true, type: :string
  # ...
end
```
but dialyzer is complaining:
```

Dialyzer warning     Function interrupt/0 has no local return
Dialyzer warning     The pattern <_@1, _@2, _@3> can never match since previous clauses completely covered the type <_,[{atom(),_}] | map(),'format' | 'from' | 'to'>
Dialyzer warning     The pattern <_@1, _@2> can never match since previous clauses completely covered the type <[{atom(),_}] | map(),'ok' | {'error',{'validation',map()}}>
```

So far, I have worked around the issue by suppressing dialyzer output for certain functions in certain modules:
```elixir
defmodule MyModule do
  use Exop.Operation
  @dialyzer [{:nowarn_function, interrupt: 0},
             {:no_match, [output: 2, put_into_collection: 3]}]
  # ...
end
```

But this is pretty much noise, these lines have no place in the application code. It would be very nice if you could somehow resolve this in the exop package itself. I am still learning Elixir, so sorry for not submitting a PR instead.

**Comment by madeinussr** [comment]
Hi, @smanolloff , thank you for submitting an issue. I will take a look into this.

Is there any `interrupt/0` invocation within `process/1` of your operation module?

**Comment by smanolloff** [comment]
Hi, and thanks for your response!

No, there is no `interrupt/0` call anywhere. My `process/1` function is actually a no-op. I am using exop only for validating the input parameters of requests in a web API. 

Oh, and sorry for not including this info earlier, in case it is relevant:
* macOS 10.13.2
* Elixir 1.6.5 (compiled with OTP 20)
* Dialyzer version v3.2.4
* exop 0.5.0

**Comment by madeinussr** [comment]
@smanolloff unfortunately I don't use Sublime Text (VS Code user here), I've launched Credo & Dialyzer, fixed some warnings and Dyalizer doesn't complain anymore. But it didn't show me such errors you shared with me above.

<img width="952" alt="screenshot 2018-07-09 21 41 30" src="https://user-images.githubusercontent.com/1419763/42469802-735c9fde-83c1-11e8-8cf0-6e575390656a.png">

mb your plugins can point to specific lines?

**Comment by drozdzynski** [comment]
Hello I using VSCode with ElixirLS and have this errors in `mix dialyzer`:
```
lib/operations/item.ex:1: Invalid type specification for function 'Operations.Item.Read':do_authorize/3. The success typing is ('Policy.Item','can_read?',[{'id',_},...]) -> 'ok'
lib/operations/item.ex:1: The pattern <'nil', __@1, __@2> can never match the type <'Policy.Item','can_read?',[{'id',_},...]>
lib/operations/item.ex:1: The pattern <__@1, 'nil', __@2> can never match the type <'Policy.Item','can_read?',[{'id',_},...]>
lib/operations/item.ex:1: Function interrupt/0 has no local return
lib/operations/item.ex:1: Function interrupt/1 has no local return
lib/operations/item.ex:1: The pattern <#{'opts':=__@2, 'module':=__@1}, __@3, __@4> can never match the type <'nil',map(),{'error',{'validation',map()}} | {'interrupt',_}>
lib/operations/item.ex:1: The pattern <__@1, __@2> can never match since previous clauses completely covered the type <map(),'ok' | {'error',{'validation',map()}}>
lib/operations/item.ex:1: The pattern <__@1, __@2, __@3> can never match since previous clauses completely covered the type <_,map(),'a' | 'user'>
lib/operations/item.ex:1: The pattern __@7 = {'ok', _} can never match the type {'error',{'validation',map()}} | {'interrupt',_}
lib/operations/item.ex:1: The pattern {'ok', __@2} can never match the type {'error',{'validation',map()}} | {'interrupt',_}
lib/operations/item.ex:9: Function process/1 has no local return
lib/operations/item.ex:10: The call 'Operations.Item.Read':do_authorize('Policy.Item','can_read?',__@3::[{'id',_},...]) breaks the contract ('Elixir.Exop.Policy':t(),atom(),'Elixir.Keyword':t()) -> auth_result()
```

**Comment by madeinussr** [comment]
thank you @drozdzynski for reporting dialyzer complains, will continue to work on it
hope will deal with it soon and they be handled in the next release
