### ISSUE TITLE
Support `mix format`

### ISSUE THREAD

**Issue by sobolevn** [madeinussr/exop#23]
Currently `mix format` does not math the provided dsl.

It formats `operation Some.Module` and `parameter :index, type: :integer` as `operation(Some.Module)` and `parameter(:index, type: :integer)`.

Which I thing is not what you want (and what is shown in the docs).
So, to fix it possible to provide `lib/exop/.formatter.exs` file with list of dsl functions: https://hexdocs.pm/mix/master/Mix.Tasks.Format.html#module-importing-dependencies-configuration

What do you think?

**Comment by madeinussr** [comment]
Hi @sobolevn ,

thank you for your feedback and proposition. Due to the fact, I'm ok with current formatter behavior and the absence of such complains I have never thought about it (docs were written before formatter has been presented). 
I will consider to add it to the next 1.2.4 ver.
👍

**Comment by madeinussr** [comment]
...you're more than welcome to provide this small PR if you wish of course :)

**Comment by madeinussr** [comment]
the change has been pushed into 1.2.4 ver. branch: https://github.com/madeinussr/exop/commit/f324fd8fa5dcbb9a9ee9ab20ca769ea805942251

thank you again for the feedback

**Comment by sobolevn** [comment]
Awesome! @madeinussr I will soon open-source a rather big project that is build upon `exop`.
Excellent tool.

Stay tuned: https://github.com/wemake-services/kira
More about the project (I assume that you do understand Russian): https://huntflow.ru/insight/article/u-nas-net-privychnoi-sistemy-motivacii-my-prosto-khorosho-platim

**Comment by madeinussr** [comment]
https://github.com/wemake-services/kira - subscribed

Yes, I've already read your article about team management approach in your company. 👍
