### ISSUE TITLE
Allow func validations to return :ok in case of successful check

### ISSUE THREAD

**Issue by ppraisethesun** [madeinussr/exop#36]
Validations should follow common conventions in elixir functions and return `:ok | {:error, reason}` tuples

**Comment by madeinussr** [comment]
which validations do you mean?

**Comment by madeinussr** [comment]
Ok, I think that was about `func` check and it's output. `:ok`\`:error` tuple output for the `func` check to consider in the next major release. Thank you.

**Comment by madeinussr** [comment]
Oops) will keep it for a while
