### ISSUE TITLE
Unify returned tuples

### ISSUE THREAD

**Issue by madeinussr** [madeinussr/exop#4]
Always return two-items tuple as result {:ok, result} or {:error, "message"} or {:error, {:validation, {...}}.

**Comment by fazibear** [comment]
Hi, thanks for fast changes!
Notice that you should be able to return error from inside of operation, not only on validation error. Sometimes even when validation passes, something else can break. Now when I return `{:error, "Can't find user"}` operation return `{:ok, {:error, "Can't find user"}} witch is bad.
I think process function should always return tuple {:ok, ...} or {:error, ...}.

Maybe behaviours is good way to implement it ?

**Comment by madeinussr** [comment]
Thanks for response.
I understand your requirement. You are talking about behaviour-based restrictions for the code within process/1 the return types. Personally I don't like {:ok, :ok} too, but Behaviors don't guarantee the code will return either :ok or :error as we expect (we should treat everything except :ok as :error, is it good?). I mean, if passed params passed the contract and process/1 was invoked successfully it is {:ok, result} (whatever result is), {:error, reasons} otherwise (except exceptions during invocation). Anyway, I'll think about it, for sure. If I didn't understand you correctly, you can propose PR, we'll review it.

**Comment by madeinussr** [comment]
"we should treat everything except :ok as :error, is it good?" I think this is the main question, actually

**Comment by madeinussr** [comment]
Oops
