### ISSUE TITLE
Type validation failures should be more descriptive

### ISSUE THREAD

**Issue by sgilson** [madeinussr/exop#41]
Instead of returning a generic error response like `%{:a => "has wrong type"}`, `Exop.ValidationChecks.check_type/3` should give more details.

For example:
```elixir
Exop.ValidationChecks.check_type(%{a: nil}, :a, :string)
%{:a => "has wrong type"} # current response
```
could return something like this instead:
```elixir
%{:a => "has wrong type. expected a string, got: nil"}
```
The exact format of the response is up for debate, but I think if this change were to occur, it should still start with `"has wrong type"`. I don't know how common it is for users to parse the responses of validation errors but I'm sure it happens. Those using `=~` or other flexible comparisons to parse the response would not be impacted, but anyone using exact comparisons would.

If this change is desirable, I can make a PR for it.

**Comment by madeinussr** [comment]
Hi @sgilson !

Thank you for the feedback. Actually, I've been thinking in the same way, and even at some point started to implement "there is a validation error for this parameter, the given value is..." feature.

And actually it is not only about type checking. I think all validations should have "the given value is.." functionality.

But we can start with type validation for sure.

One thing I'd like to propose: can we review all validations messages to see whether it is convenient to put `got: xyz` at the end of the error message.
I don't remember now, but there was something that doesn't allow us to apply the same pattern for all validations provided by exop.

If it is so and to implement `got: xyz` feature for all validations we need to change an operation output's format (not only 2-elements tuple), then this should be done in some major version as this feature breaks backward compatibility.

You're more than welcome to provide a PR, but please, if it is possible, take a look: which validations may have this feature also without breaking the output (basically, only change an error message is needed).

I hope I was clear :) if not - don't hesitate to ask more questions, propose other approaches.

**Comment by sgilson** [comment]
I completely agree with the approach you suggested.

It looks like the addition can be accomplished without breaking the 2-element tuple return types of the underlying validators, but the change to the validation messages will still break backwards compatibility.

**Comment by madeinussr** [comment]
the basic solution will be provided in [1.3.5](https://github.com/madeinussr/exop/tree/1.3.5)

**Comment by madeinussr** [comment]
thanks @sgilson for your effort
